spring.application.name=marketplace
management.endpoint.health.show-details=always
spring.docker.compose.lifecycle-management=start-only

# Registration (MySQL 3307)
registration.datasource.url=jdbc:mysql://localhost:3307/registration
registration.datasource.username=app
registration.datasource.password=app
registration.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
registration.jpa.properties.hibernate.hbm2ddl.auto=update

# Catalog (MySQL 3308)
catalog.datasource.url=jdbc:mysql://localhost:3308/catalog
catalog.datasource.username=app
catalog.datasource.password=app
catalog.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
catalog.jpa.properties.hibernate.hbm2ddl.auto=update